name: Publish Workflow

on:
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Get integration information
        id: information
        run: |
          name=$(find custom_components/ -type d -maxdepth 1 | tail -n 1 | cut -d "/" -f2)
          echo "name=$name" >> $GITHUB_OUTPUT
      - name: Extract version from manifest
        if: ${{ github.event_name == 'push' }}
        id: version
        run: |
          version=$(jq -r '.version' custom_components/${{ steps.information.outputs.name }}/manifest.json)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - name: Adjust version number
        if: ${{ github.event_name == 'release' || github.event_name == 'push' }}
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            tag="${{ github.event.release.tag_name }}"
          else
            tag="v${{ steps.version.outputs.version }}"
          fi
          yq -i -o json '.version="'"$tag"'"' \
            "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/manifest.json"
      - name: Create zip file for the integration
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}"
          zip ${{ steps.information.outputs.name }}.zip -r ./
      - name: 📤 Upload zip to action
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: hcs_shutter_ha
          path: ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}
          retention-days: 14
      - name: Upload the zipfile as a release asset
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/${{ steps.information.outputs.name }}.zip
          tag_name: ${{ github.event.release.tag_name }}
