name: Publish Workflow

on:
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Get integration information
        id: information
        run: |
          name=$(find custom_components/ -type d -maxdepth 1 | tail -n 1 | cut -d "/" -f2)
          echo "name=$name" >> $GITHUB_OUTPUT
      - name: Adjust version number
        if: ${{ github.event_name == 'release' }}
        shell: bash
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/manifest.json"
      - name: Create zip file for the integration
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}"
          zip ${{ steps.information.outputs.name }}.zip -r ./
      - name: 📤 Upload zip to action
        uses: actions/upload-artifact@v3.1.2
        if: ${{ github.event_name == 'push' }}
        with:
          name: hcs_shutter_ha
          path: ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}
          retention-days: 14
      - name: Upload the zipfile as a release asset
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/${{ steps.information.outputs.name }}.zip
          tag_name: ${{ github.event.release.tag_name }}
